# Generated by Django 4.1.7 on 2023-03-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issuestatus", options={"verbose_name_plural": "Statuses"},
        ),
    ]
