# Generated by Django 4.1.7 on 2023-03-02 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0004_rename_issuestatus_status_rename_issuetype_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="issue", name="type",),
        migrations.CreateModel(
            name="IssueType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="issue_types",
                        to="webapp.issue",
                        verbose_name="Задача",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="type_issues",
                        to="webapp.type",
                        verbose_name="Тип",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="issue",
            name="type",
            field=models.ManyToManyField(
                blank=True,
                related_name="issues",
                through="webapp.IssueType",
                to="webapp.type",
            ),
        ),
    ]
