# Generated by Django 4.1.7 on 2023-03-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0005_remove_issue_type_issuetype_issue_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue", old_name="type", new_name="type_old",
        ),
    ]
