# Generated by Django 4.1.7 on 2023-03-02 19:27

from django.db import migrations


def transfer_tags(apps, schema_editor):
    Issue = apps.get_model('webapp.Issue')

    for issue in Issue.objects.all():
        issue.type.set(issue.type_old.all())


def rollback_transfer(apps, schema_editor):
    Issue = apps.get_model('webapp.Issue')

    for issue in Issue.objects.all():
        issue.type_old.set(issue.type.all())


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0007_issue_type"),
    ]

    operations = [
        migrations.RunPython(transfer_tags, rollback_transfer)
    ]
