# Generated by Django 4.1.7 on 2023-03-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0008_auto_20230302_1927"),
    ]

    operations = [
        migrations.RemoveField(model_name="issue", name="type_old",),
        migrations.DeleteModel(name="IssueType",),
    ]
