# Generated by Django 4.1.7 on 2023-03-07 11:10

from django.db import migrations, models
import webapp.models.issues


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0009_remove_issue_type_old_delete_issuetype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="summary",
            field=models.CharField(
                max_length=50,
                validators=[
                    webapp.models.issues.validate_summary_exists,
                    webapp.models.issues.validate_summary_min_length,
                ],
                verbose_name="Краткое описание",
            ),
        ),
    ]
