# Generated by Django 4.1.7 on 2023-03-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0010_alter_issue_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="deleted_date",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Date of deletion"
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Deleted"),
        ),
    ]
