# Generated by Django 4.1.7 on 2023-03-09 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0011_issue_deleted_date_issue_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата начала"
                    ),
                ),
                (
                    "ended_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Краткое описание"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Полное описание",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удален"),
                ),
                (
                    "deleted_date",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="Дата и время удаления"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="issue",
            name="deleted_date",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Дата и время удаления"
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удален"),
        ),
    ]
