# Generated by Django 4.1.7 on 2023-03-09 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0013_alter_project_description_alter_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="projects",
                to="webapp.project",
                verbose_name="Проект",
            ),
            preserve_default=False,
        ),
    ]
